/** Declaration file generated by dts-gen */

declare module "atom-highlight" {
  export = highlightSync;
  interface Arguments {
      fileContents: string;
      scopeName: string;
  }
  interface DefaultOptions {
      nbsp: boolean;
      lineDivs: boolean;
      editorDiv: boolean;
      wrapCode: boolean;
      editorDivTag: string;
      editorDivClass: string;
      nullScope: string;
  }
  type Options = Partial<DefaultOptions>;
  function highlightSync(options: Arguments & Options): string;
}
